### ISSUE TITLE
Watchify?

### ISSUE THREAD

**Issue by girvo** [MadcapJake/fly-browserify#1]
Looking good! I'm testing it out now, well done :)

I wonder what the story looks like for tools such as WebPack or Watchify when it comes to Fly, in that the tasks never actually `yield` out -- they run forever. Is that a problem? Would it be simple enough to just wrap the browserify calls with watchify?

Now, I know that Fly has a `this.watch` call -- however, watchify and webpack both add a tonne of smarts to their watching to allow for incremental compilation, which Fly shouldn't duplicate unnecessarily, I think!

**Comment by MadcapJake** [comment]
If you want to integrate `watchify` with fly, I think another plugin would be necessary.  The function would initialize the browserify compiler on first load and then when `this.watch` runs the task again, it would just call `bundle()`.  Another thought would be to have two functions, one for initialization of the bundle and another for bundling in a watch task.  Either way, due to browserify's nature, it still suffers from eagerly doing all the file work on it's own so it would have to `unwrap` on initialization (like this plugin) and then when `bundle` is called in the watch task, it would actually do the file io itself.

When @bucaran gets CSP in, both browserify and a watchify plugin would benefit. :+1: 

As far as webpack, there is [gulp-webpack-build](https://github.com/mdreizin/gulp-webpack-build) that I've been looking at either importing or refactoring into a fly plugin.  I think it will be more complicated than browserify, but I would like to see a `fly-webpack` plugin though!

**Comment by girvo** [comment]
@bucaran Hey just checking, is CSP in Fly now?

**Comment by ghost** [comment]
@girvo No, and it's very unlikely it will be. The good news is that @lukeed and I are planning rewriting Fly into a smaller, more self-contained library. Also, it will be in ES5 avoiding the transpilation step. Imagine how exciting, `npm i fly` and it will be done before you can take a shower.

**Comment by lukeed** [comment]
What's CSP? Sorry

Also, why not just run a watcher on your scripts, and also install browsersync? Then, on each task run, call browsersync.reload and you'll have replicated watchify in its entirety! 

This is what I do, at least. 

Check out my fly-kit-web repo. I'd link to it directly but I'm on my phone

**Comment by lukeed** [comment]
@girvo back to a computer...

Relevant lines:
- [this](https://github.com/lukeed/fly-kit-web/blob/master/flyfile.js#L2)
- [this](https://github.com/lukeed/fly-kit-web/blob/master/flyfile.js#L49)
- and [this](https://github.com/lukeed/fly-kit-web/blob/master/flyfile.js#L149)

Notice the "environment handling" with use of `isWatch && isServer` -- don't always want a `reload()` to fire; eg, when I'm running a single build for production.

**Comment by girvo** [comment]
@lukeed Yeah that's exactly how I've tackled it so far :) 

In addition, I've utilised `webpack` for JS module building, and a task to run `webpack-dev-server` which honestly handles the bulk of what I needed; I utilise fly as a task running to kick it off, and `require('./assets/css/styles.css')` (the compiled CSS, result of `fly css`) to get live-reload functionality of Javascript and CSS for development. Run `fly watch`, it starts a regular CSS watch task and the `watchJs` task called with my webpack config :)

``` js
const config = {
    webpack: require('./webpack.config.js')
}

export function* css() {
    yield this
        .source('styles/main.css')
        .postcss({
            plugins: [
                require('postcss-import'),
                require('precss'),
                require('autoprefixer')
            ],
            options: {
                parser: require('postcss-scss')
            }
        })
        .concat('styles.css')
        .target('web/assets/css')
}

export function* webpack() {
    yield this
        .source('src/index.js')
        .webpack(config.webpack)
}

export function* watchJs() {
    let webpackDevServer = require('webpack-dev-server')
    let webpack = require('webpack')

    yield new Promise((resolve, reject) => {
        let compiler = webpack(config.webpack)
        let server = new webpackDevServer(compiler, config.webpack.devServer)
        this.log('Starting webpack-dev-server on port 8080\n')
        server.listen(8080);
    });
}

export function* watch() {
    yield this.watch(['styles/**/*.css'], 'css')
    yield this.start(['watchJs'])
}
```

`webpack.config.js`:

``` js
var webpack = require('webpack')
var path = require('path')

module.exports = {
    entry: './src/index.js',

    output: {
        path: path.resolve(__dirname, 'web', 'assets', 'js'),
        publicPath: '/assets/js/',
        file: 'app.js'
    },

    module: {
        loaders: [
            {
                // Load ES2015
                test: /\.jsx?$/,
                loader: 'babel?presets[]=es2015'
            },
            {
                // This loader is used for our webpack-dev-server
                test: /\.css$/,
                loader: 'style!css'
            }
        ]
    },

    // This can be changed to proxy through to a PHP/Node app
    devServer: {
        contentBase: './web/',
        inline: true,
    }
}
```

This gets the behaviour I'm after for now at least!

**Comment by lukeed** [comment]
Lol, wait, so do you need help still? :confused:

**Comment by girvo** [comment]
Oh! No, not really, I've just been diving into some `fly` stuff recently and came across this old issue, thought I'd check in :)

**Comment by lukeed** [comment]
Haha, ok :) 

Looks like you'd save a lot of headache by kicking off with that fly-kit-web I linked. You'll just need to add/keep `fly-webpack` and the rest should work out of the box. Tunnel browserify into webpack, and pass a babel hook-up through as a browserify transform or a webpack loader. Then, just trigger the `reload` at the end of the task, if desired.

All the best & Good luck!
