### ISSUE TITLE
TypeError: this.unwrap is not a function

### ISSUE THREAD

**Issue by ngryman** [MadcapJake/fly-browserify#8]
Hi,

This happens with a fresh install of `fly@1.4.1`, `fly-esnext@1.0.1` and `fly-browserify@1.0.0`.

Any idea?
Thanks!

**Comment by lukeed** [comment]
What version of Node are you on?

**Comment by ngryman** [comment]
``` sh
~  🚀  node -v
v6.5.0
```

**Comment by lukeed** [comment]
Sorry @ngryman, somehow I missed this! 

Fly's `unwrap` method was removed in `1.4.0`, so you have to hard-require `fly@1.3.2` if you want to use version `1.0.0` of this plugin.

I've had a PR open to upgrade this plugin to `2.0` for 2 weeks now... doesn't seem that @MadcapJake is active anymore. Bummer.

So I'm maintaining `2.0` on [my fork](https://github.com/lukeed/fly-browserify). It will require `fly@beta` for now, while Fly finishes its last bits.
